---
title: "Spring Trend Grading Rubric"
output: html_document
---


## Group Project Requirements
  - Collecting tweets using either the stream_tweets or search_tweets function. Make sure to justify why you use
    one over the other.
  - Creating an R Markdown document which includes these elements: leaflet map, plot, and at least five linked pictures.
    One of these pictures should be a wordcloud which includes most commonly occuring words. You only need to do this 
    for at least 100 tweets! You can use this [website](https://www.jasondavies.com/wordcloud/) in order to make
    your WordCloud or you can choose whatever website you want! 
  
## Spring Trends
  1. MLB Baseball
  2. Spring Break
  3. Allergies
  4. March Madness
  
## Grading Rubric
  1. Overview of the spring trend. <b>10 points</b>
  2. Techniques used(stream_tweets or the search_tweets funcion? What search terms did you use?) <b>10 points</b>
  3. How many tweets did you collect? Give the time period in which you collected tweets. <b>10 points</b>
  4. Wordcloud of common themes. <b>4 points</b>
  5. Four other linked images. <b>10 points</b>
  6. Leaflet Map. <b>10 points</b>
  7. Plot showing frequency of tweets over a time period using the ts_plot package. <b>6 points</b>
  8. How many tweets did you collect? Give the time period in which you collected tweets. <b>10 points</b>
  9. Issues encountered while collecting tweets. <b>10 points</b>
  10. Creating an R Markdown Presentation which includes the major elements of the project. <b>10 points </b>
  11. Presentation flow(making sure the presentation is cohesive and all members taking a part). <b>10 points</b>
  
Make sure to publish your R Markdown presentation and R Markdown document on RPubs. You can attach a link to your documents in a Word document and submit them to ELC. Only one person per group needs to submit a link. Make sure to put the name of your team members on your Word document, R Markdown presention, and R Markdown document. Points will be taken off you fail to do this!
  
### Total Points: 100

